program: src/train.py
method: bayes
metric:
  name: val_acc
  goal: maximize
parameters:
  arch:
    value: resnet
  csv:
    value: fer2013.csv
  group:
    value: resnet_sweep
  name:
    value: sweep_run
  augment:
    value: "true"
  epochs:
    value: 40
  lr:
    distribution: log_uniform_values
    min: 0.00005
    max: 0.005
  wd:
    values: [0, 0.0001, 0.0005]
  dropout:
    values: [0.3, 0.4, 0.5]
  optimizer:
    values: [adam]
  batch:
    values: [32, 64]
  label_smooth:
    values: [0.0, 0.1]
  sched:
    values: [cosine, plateau]
